# 🔧 GRB Fit Configuration File

burst:
  name: GRB240205B
  t0: 1.0
  t0_rev: 0.05
  fitstart: 0.01
  z: 0.824

data:
  radio_file: grbmeas.csv
  other_file: otherdata.txt
  batxrt_file: null
  xrt_photon_index: null
  # Unabsorbed flux / observed flux from the XRT spectrum.
  absorption_ratio: null

model:
  type: forward_reverse   # options: forward_only, forward_reverse
  k: 2
  p: 2.2

fit:
  initial_guess:
    f0: 1e-3
    f0_rev: 5e-4
    nua0_rev: 10
    num0_rev: 500
    nuc0_rev: 8e8
    nua_0: 13
    num_0: 2e4
    nuc_0: 8e8
    t_j: null
  bounds:
    # Set lower and upper equal to remove a parameter from fitting.
    # The fixed value will be the corresponding initial_guess value.
    f0: [5e-4, 1e2]
    f0_rev: [1e-5, 1]
    nua0_rev: [1, 50]
    num0_rev: [10, 1000]
    nuc0_rev: [8e8, 8e8]
    nua_0: [1, 100]
    num_0: [100, 1e5]
    nuc_0: [8e8, 8e8]
    t_j: [200, 200]
  max_rest_freq: 2.47e6 # GHz, FUV in rest frame, only used in z is defined.
  fit_xrt: false
